/* =========================
 * src/core/warnings.ts
 * ========================= */

export const W = {
  GEOM_INVALID: "GEOM_INVALID",
  GEOM_NO_CHANNEL: "GEOM_NO_CHANNEL",
  DFM_FIN_SPACING_LOW: "DFM_FIN_SPACING_LOW",
  FLOW_AREA_TOO_SMALL: "FLOW_AREA_TOO_SMALL",
  FAN_NON_MONOTONE: "FAN_NON_MONOTONE",
  FAN_DP_NEGATIVE_CLAMPED: "FAN_DP_NEGATIVE_CLAMPED",
  NO_OPERATING_POINT: "NO_OPERATING_POINT",
  ITER_NOT_CONVERGED: "ITER_NOT_CONVERGED",
  RE_OUT_OF_RANGE: "RE_OUT_OF_RANGE",
  MODEL_SIMPLIFIED: "MODEL_SIMPLIFIED",
  BUDGET_NEGATIVE: "BUDGET_NEGATIVE",
} as const;
